name: Merge main to deploy

on:
  push:
    branches:
      - main

jobs:
  merge-to-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Merge main to deploy
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git checkout deloy-backend
        git merge --no-ff main -m "Auto-merge to deploy-backend branch"
        git push origin deloy-backend
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
